## Import NumPy

In [4]:
import numpy as np

In [5]:
## why use NumPy?

## Array Numpy lebih cepat dan lebih compact daripada List Python. Sebuah array mengkonsumsi lebih sedikit memori dan jauh lebih convenient untuk digunakan. Numoy menggunakan lebih sedikit memori untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, yang memungkinkan kode untuk dioptimalkan lebih jauh.


In [6]:
## aray adalah grid of values dan berisi informasi tentang data mentah, cara menemukan elemen, dan cara menginterpretasikan elemen.

## Salah satu cara kita dapat menginisialisasi array NumPy adalah dari nested Python lists.
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(a[0])

[1 2 3 4]


In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
print(np.arange(4))
print(np.arange(0,10,2))  # (start, stop, step)

# apa yang dilakukan arange([start],stop,[step]) adalah mengatur angka dari awal sampai berhenti. ini adalah arti dari np.arange(0,10,2):

[0 1 2 3]
[0 2 4 6 8]


In [12]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [14]:
arr1 = np.append(arr, [1,2])  # menambahkan elemen ke array
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [15]:
np.delete(arr, 1)  # menghapus elemen di posisi 1 dari array

array([1, 3, 4, 5, 6, 7, 8])

In [16]:
np.delete(arr1, 1)

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)  # mengurutkan angka dalam urutan menaik

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [18]:
## ndarray.ndim()  # memberi tahu jumlah axes, atau dimensi dari array
## ndarray.size()  # memberi tahu jumlah total elemen array
## ndarray.shape()  # menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array. jika memiliki larik 2D dengan 2 baris dan 3 kolom, maka bentuk larik adalah (2,3)

In [19]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                         
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                         
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [20]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [21]:
array_example.ndim

3

In [22]:
array_example.size

24

In [23]:
array_example.shape

(3, 2, 4)

In [24]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [25]:
arr_one.size

5

In [26]:
arr_one.shape

(1, 5)

## Reshape

In [27]:
# menggunakan np.reshape() akan memberikan bentuk baru ke array tanpa mengubah datanya.

In [28]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [30]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [31]:
a.reshape(6,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [32]:
## dapat menggunakan np.newaxis dan np.expand_dims untuk meningkatkan dimensi array yang sudah ada.

## menggunakan np.newaxis akan meningkatkan dimensi array kalian sebesar satu dimensi bila digunakan 

In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
# pakai np.newaxis untuk axis baru
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
# convert 1D array untuk baris vektor dengan memasukkan sumbu sepanjang dimensi pertama

In [36]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [37]:
# untuk kolom vektor, kita dapat memasukkan sumbu sepanjang dimensi kedua

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
# kita dapat memperluas array dengan memasukkan axis baru pada posisi yang ditentukan dengan np.expand_dims

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
# gunakan np.expand_dims untuk menambahkan sumbu pada indeks posisi 1

b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [40]:
# add an axis ar index position 0

c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

## Indexing and Slicing

In [41]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])


[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [42]:
## memilih nulai dari array yang memenuhi kondisi tertentu, dapat dilakukan dengan Numpy

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# you can easily print all of the values in the array that are less than 5

print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [44]:
## dapat memilih, angka yang sama dengan atau lebih besar dari 5, dan menggunakan kondisi tersebut untuk mengindeks array

five_up = (a >= 5)

print(a[five_up])
print(a[a >= 9])

[ 5  6  7  8  9 10 11 12]
[ 9 10 11 12]


In [45]:
## you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [46]:
# you can select element that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [48]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [49]:
a_1= np.array([[1, 1],
      [2, 2]])

In [50]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [51]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [52]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [53]:
# membagi sebuah  array menjaid beberapa array yang lebih kecil menggunakan hsplit. dapat menentukan jumlah array yang bentuknya sama untuk dikembalikan atau kolom setelah pembagian dilakukan.
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [55]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [56]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
c = a.copy()
c 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [ ]:
## Addition, subtraction, multiplication, division, and more.
# data - ones
# data * data
# data / data

In [59]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [60]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [61]:
# sum the row
b.sum(axis = 0)

array([3, 3])

In [62]:
b.sum(axis = 1)

array([2, 4])

In [63]:
data = np.array([1, 2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data * data

array([1, 4])

In [67]:
data / data

array([1., 1.])

## Broadcasting

In [68]:
data * 1.6

array([1.6, 3.2])

In [69]:
data * 2

array([2, 4])

## More Array Operations

In [70]:
# Maximum, minimum, sum, mean, product, standard deviation, and more

In [71]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [72]:
print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [73]:
A.sum()

4.8595784

In [74]:
A.min()

0.05093587

In [75]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [76]:
A.max()

0.82485143

In [77]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [79]:
A.std()

0.21392120766089617

## Matrices

### Creating Matrices

In [82]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.42196131 0.3302857 ]
 [0.75276494 0.71886376]
 [0.75918737 0.93833145]]


In [83]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [84]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [85]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [86]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [87]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [88]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [89]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [91]:
data = np.array([[1, 2], [3, 4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [92]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [93]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [94]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [96]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [97]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [98]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [99]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [101]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [102]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [103]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [104]:
print(np.random.random((4,3,2)))

[[[0.3778892  0.33324772]
  [0.74327464 0.3083999 ]
  [0.86645138 0.90637972]]

 [[0.74114083 0.13971144]
  [0.33233716 0.08269291]
  [0.73657981 0.48346946]]

 [[0.07870719 0.45512786]
  [0.24523944 0.80933213]
  [0.40178585 0.00237254]]

 [[0.50494204 0.3819102 ]
  [0.07858426 0.4024034 ]
  [0.69598437 0.84070819]]]


## Flatten N-Dimensional Array

In [105]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [106]:
# You can use flatten to flatten your array into a 1D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [108]:
# menerapkan rumus sederhana ini
# error = (1/n) * np.sum(np.square(observed - prediction))