# Descriptive Statistics

In [3]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [4]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [5]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


# Measures of Central Tendency

Measures of Central Tendency menunjukkan nilai tengah atau pusat dari kumpulan data. Ada beberapa definisi tentang apa yang dianggap sebagai pusat kumpulan data.

### Mean

In [6]:
mean_ = sum(x) / len(x)
mean_

8.7

In [7]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [8]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [9]:
mean_ = np.mean(y)
mean_

8.7

In [10]:
mean_ = y.mean()
mean_

8.7

In [11]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [12]:
np.nanmean(y_with_nan)

8.7

In [13]:
mean_ = z.mean()
mean_

8.7

In [14]:
z_with_nan.mean()

8.7

## Weighted Mean

weighted arithmetic mean atau weighted average, adalah generalisasi dari rata-rata aritmatika yang memungkinkan kita untuk menentukan kontribusi relatif dari setiap titik data ke hasil

In [15]:
0.2 * 2 + 0.5 * 4 + 0.3 * 8

4.8

In [16]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

6.95
6.95


In [17]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [18]:
(w * y).sum() / w.sum()

6.95

## Harmonic Mean

In [19]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [20]:
# atau
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [21]:
# atau
scipy.stats.hmean(y)
scipy.stats.hmean(z)

2.7613412228796843

## Geometric Mean

In [22]:
gmean = 1
for item in x:
    gmean *=item
    
gmean **=1 / len(x)
gmean

4.677885674856041

In [23]:
scipy.stats.gmean(z)

4.67788567485604

### Median

In [24]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
    
median_

4

In [25]:
x

[8.0, 1, 2.5, 4, 28.0]

In [26]:
statistics.median_low(x[:-1])

2.5

In [27]:
statistics.median_high(x[:-1])

4

In [28]:
print(x_with_nan)
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

[8.0, 1, 2.5, nan, 4, 28.0]
6.0
4
8.0


In [29]:
median_ = np.median(y)
print(median_)

4.0


In [30]:
median_ = np.median(y[:-1])
print(median_)

3.25


### Mode

In [31]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

In [32]:
mode_ = statistics.mode(u)
mode_

2

In [33]:
# kita bisa mendapatkan mode dengan scipy.stat.mode():

u, v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [34]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [35]:
# kita bisa mendapatkan mode dan jumlah kemunculannya sebagai array NumPy dengan dot notation:

print(mode_.mode)
print(mode_.count)

[12]
[3]


In [36]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int32
0    12
1    15
dtype: int32
0    2.0
dtype: float64


### Measures of Variability

In [37]:
# cara menghitung sample variance dengan Python pure:
n = len(x)
mean_ = sum(x) / n

var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

In [38]:
# solusi yang lebih singkat dan lebih elegan adalah dengan memanggil fungsi statistics.variance():

var_ = statistics.variance(x)
var_

123.2

In [39]:
# menghitung sample variance dengan NumPy, gunakan fungsi np.var() atau method.var():

var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [40]:
z.var(ddof=1)

123.19999999999999

### Standard Deviation

In [41]:
std_ = var_ ** 0.5
std_

11.099549540409285

In [42]:
# atau dengan menggunakan
std_ = statistics.stdev(x)
std_

11.099549540409287

In [43]:
np.std(y, ddof=1)

11.099549540409285

In [44]:
y.std(ddof=1)

11.099549540409285

### Skewness

In [45]:
x = [8.0, 1, 2.5, 4, 28.0]

n = len(x)

mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ =var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x) * n / ((n-1) * (n-2) * std_**3))
         
skew_

1.9470432273905929

In [46]:
y, y_with_nan = np.array(x), np.array(x_with_nan)

scipy.stats.skew(y, bias=False)

1.9470432273905927

In [47]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [48]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [49]:
z_with_nan.skew()

1.9470432273905924

### Percentiles

In [50]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
statistics.quantiles(x, n=2)

[8.0]

In [51]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [52]:
y = np.array(x)
np.percentile(y, 5)

-3.44

In [53]:
np.percentile(y, 95)

34.919999999999995

In [54]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [55]:
np.median(y)

8.0

In [56]:
y_with_nan = np.insert(y, 2, np.nan)
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [57]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [58]:
np.quantile(y, 0.05)

-3.44

In [59]:
np.quantile(y, 0.95)

34.919999999999995

In [60]:
np.quantile(y, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [61]:
np.nanquantile(y_with_nan, [0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [62]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-3.44

In [63]:
z.quantile(0.95)

34.919999999999995

In [64]:
z.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [65]:
z_with_nan.quantile([0.25, 0.5, 0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [66]:
np.ptp(y)

46.0

In [67]:
np.ptp(z)

46.0

In [68]:
np.ptp(y_with_nan)

nan

In [69]:
np.ptp(z_with_nan)

nan

In [70]:
np.amax(y) - np.amin(y)

46.0

In [71]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [72]:
y.max() - y.min()

46.0

In [73]:
z_with_nan.max() - z_with_nan.min()

46.0

In [74]:
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [75]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

### Summary of Descriptive Statistics

In [76]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [77]:
result.nobs

9

In [78]:
result.minmax[0]  # Min

-5.0

In [79]:
result.minmax[1]  # Max

41.0

In [80]:
result = z.describe()
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

### Measures of Correlation Between Pairs of Data

In [81]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

In [82]:
x

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [83]:
y

[0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

### Covariance

In [84]:
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n

In [85]:
mean_x

0.0

In [86]:
mean_y

5.714285714285714

In [87]:
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) fot k in range(n)) 
          / (n-1))
cov_xy

SyntaxError: invalid syntax (2199012012.py, line 1)

In [88]:
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [89]:
x_.var(ddof=1)

38.5

In [90]:
y_.var(ddof=1)

13.914285714285711

In [91]:
cov_xy = cov_matrix[0, 1]
cov_xy

19.95

In [92]:
cov_xy = cov_matrix[1, 0]
cov_xy

19.95

In [93]:
cov_xy = x__.cov(y__)
cov_xy

19.95

In [94]:
cov_xy = y__.cov(x__)
cov_xy

19.95

### Correlation Coefficient

In [97]:
var_x = sum((item - mean_x)**2 for item in x) / (n - 1)
var_y = sum((item - mean_y)**2 for item in y) / (n - 1)\
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

SyntaxError: invalid syntax (779569328.py, line 3)